[project]
name = "pgnparser"
version = "0.1.0"
description = "Programm zum Erstellen eines Variantenbaums aus einer pgn-Notation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
